### ISSUE TITLE
Create a GameService

### ISSUE THREAD

**Issue by oldskoolfan** [csci-2479-au-2022/tabletop-nerds#12]
As an application I want a GameService I can depend on that will be responsible for retrieving both a single game result and a list of game results, optionally filtered by basic search parameters.

Acceptance Criteria:
- A GameService with the following public methods:
  - getGameById with `$id` param
  - getGames with optional `$orderBy`, `$direction`, and `$limit` params
  - searchGamesByTitle with the `$title` param
  - update the GameController to depend on this service and call `getGames` in the listGames endpoint
  - update the SearchResultController to depend on this service and call `searchGamesByTitle` in the search endpoint

**Comment by lrapp1** [comment]
I do not know what you mean by the last two bullet-points, does endpoint mean like the view page?

Regarding updating controller dependencies, I just added "use App\Http\Services\GameService;", did you mean removing Controller and extending or implementing GameService instead?

**Comment by oldskoolfan** [comment]
Here's an example of what I mean by updating the controllers to depend on the service: https://github.com/csci-2479-au-2022/in-class-examples/pull/2/files#diff-e74a1e9d4e2d6366d6b69b0918e117bc9d1459bc746658131eeea75046f60783.

In this example it's an interface, but we can also do it with a concrete class as well. Let me know if this helps.

**Comment by oldskoolfan** [comment]
Also endpoint is a loose term referring to the route and controller method called by the route. I that case I specifically meant the controller methods. Sorry for the confusion.

**Comment by lrapp1** [comment]
Thanks for the comment, I'll try and take a look before class tonight. I'm also pretty sure you talked about endpoints before and I just didn't listen well enough.
