### ISSUE TITLE
Add toggleWishlist feature to Game Details view

### ISSUE THREAD

**Issue by oldskoolfan** [csci-2479-au-2022/tabletop-nerds#39]
Game details page should display a button with the ability to add or remove the game to the user's wishlist

### Acceptance Criteria
 - a button would only display if the user is logged in
 - if the user already has the game on their wishlist, the button would let the user remove the game from their wishlist
 - if the game is not on their wishlist, the button would allow the user to add the game to their wishlist

#### frontend requirements
 - a game alpineJS component similar to the pet component that is a function that accepts arguments for gameId and isOnWishlist
 - a toggleOnWishlist method that accepts a userId and calls the /toggle-wishlist route in issue #36 using axios
    - on success this method should update the isOnWishlist state accordingly
 - a blade component for pet-details that uses the alpineJS pet component to display the toggleWishlist button (see the pet blade component as an example)

**Comment by lrapp1** [comment]
Merged into main
